name: MacOS Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Coverage

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install gcovr
      run: brew install gcovr

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Test

    - name: Build the project
      run: cmake --build ${{github.workspace}}/build
      
    - name: Generate code coverage reports
      run: cd build && make projecto_coverage
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
